[tool.poetry]
name = "atcoder"
version = "0.1.0"
description = ""
authors = ["kyuuri0119"]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.2"
scipy = "^1.11.4"


[tool.poetry.dev-dependencies]

[build-system]

requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.ap"
